name: poa-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - networkx
  - cvxpy
  - pip
  - scikit-learn
  - scipy
  - pillow
  - jupyter
  - notebook
  - pip:
      - dccp